//! The pure aggregate mutations: given the current document, an already-typed
//! input, freshly allocated ids, and a timestamp, produce the next document or
//! a typed error. These functions never touch a clock, an id source, or the
//! repository, so they stay deterministic and directly testable — the facade in
//! [`crate::lib`] wires them to the transaction.

use serde_json::Value;

use crate::error::{CoreError, ValidationError};
use crate::model::{HatchPet, Patch, PetId, PetPatch, SettingsPatch};
use crate::personalities::personality_preset;
use crate::queries::find_pet_id_by_cwd;
use crate::state_v1::{empty_state, push_array, PET_DATA_KEYS};
use crate::working_directory::{comparable_path, is_valid_working_directory};
use crate::{asset_id, WorkingDirectoryPath};

/// The ids a Pet Birth needs, generated by the caller so [`apply_hatch`] stays
/// pure.
pub(crate) struct HatchIds {
    pub pet_id: String,
    pub profile_id: String,
    pub working_directory_id: String,
    pub agent_source_id: String,
}

/// The ids a working-directory re-bind needs (mirrors [`HatchIds`]).
pub(crate) struct WorkingDirectoryIds {
    pub working_directory_id: String,
    pub agent_source_id: String,
}

/// Pet Birth: create the Pet and its Pet Profile atomically, plus a Registered
/// Working Directory when a folder was supplied. Rejects an unknown
/// personality, an unusable folder path, and a folder already held by another
/// pet — leaving the document unchanged in every rejection.
pub(crate) fn apply_hatch(
    state: &Value,
    input: &HatchPet,
    ids: &HatchIds,
    now: u64,
) -> Result<Value, CoreError> {
    let personality = personality_preset(&input.personality_id)
        .ok_or(ValidationError::UnknownPersonality)?;

    if let Some(cwd) = &input.working_directory {
        if !is_valid_working_directory(cwd.as_str()) {
            return Err(ValidationError::InvalidWorkingDirectory.into());
        }

        if let Some(owner_pet_id) = occupant_of(state, cwd) {
            return Err(CoreError::WorkingDirectoryOccupied { owner_pet_id });
        }
    }

    let mut next = state.clone();

    push_array(
        &mut next,
        "pets",
        serde_json::json!({
            "id": ids.pet_id,
            "workingDirectoryId": input.working_directory.as_ref().map(|_| ids.working_directory_id.clone()),
            "assetId": input.asset_id,
            "profileId": ids.profile_id,
            "name": input.name,
            "adoptedAt": now,
            "archived": false,
            "visible": true
        }),
    );
    push_array(
        &mut next,
        "petProfiles",
        serde_json::json!({
            "id": ids.profile_id,
            "petAssetId": input.asset_id,
            "personalityId": input.personality_id,
            "personality": personality
        }),
    );
    // A pet can be adopted with no folder bound: it lives on and receives no
    // agent events until one is picked from its settings.
    if let Some(cwd) = &input.working_directory {
        push_array(
            &mut next,
            "registeredWorkingDirectories",
            serde_json::json!({
                "id": ids.working_directory_id,
                "path": cwd.as_str(),
                "petId": ids.pet_id,
                "agentSourceId": ids.agent_source_id,
                "createdAt": now,
                "updatedAt": now
            }),
        );
    }

    Ok(next)
}

/// The pet id that already holds `cwd`, comparing folders case- and
/// separator-insensitively.
fn occupant_of(state: &Value, cwd: &WorkingDirectoryPath) -> Option<String> {
    let target = cwd.comparable();
    state
        .get("registeredWorkingDirectories")
        .and_then(|value| value.as_array())?
        .iter()
        .find(|directory| {
            directory
                .get("path")
                .and_then(|value| value.as_str())
                .map(|path| comparable_path(path) == target)
                .unwrap_or(false)
        })
        .map(|directory| {
            directory
                .get("petId")
                .and_then(|value| value.as_str())
                .unwrap_or_default()
                .to_string()
        })
}

/// Apply a partial patch to one pet record (and its profile's personality and
/// mirrored asset id, when set). Unset fields are left untouched; a rejected
/// re-bind leaves the other patched fields unwritten too.
pub(crate) fn apply_pet_update(
    state: &Value,
    pet_id: &PetId,
    patch: &PetPatch,
    ids: &WorkingDirectoryIds,
    now: u64,
) -> Result<Value, CoreError> {
    let pet_exists = state
        .get("pets")
        .and_then(|value| value.as_array())
        .is_some_and(|pets| {
            pets.iter()
                .any(|pet| pet.get("id").and_then(|value| value.as_str()) == Some(pet_id.as_str()))
        });

    if !pet_exists {
        return Err(CoreError::PetNotFound {
            pet_id: pet_id.as_str().to_string(),
        });
    }

    let personality = match &patch.personality_id {
        Some(personality_id) => match personality_preset(personality_id) {
            Some(personality) => Some(personality),
            None => return Err(ValidationError::UnknownPersonality.into()),
        },
        None => None,
    };

    // The asset id is addressed as a directory name by the sprite loader and as
    // a query parameter by the pet overlay window, so reject anything those two
    // could not resolve before it reaches disk (same guard as hatching).
    if let Some(asset_id) = &patch.asset_id {
        if !asset_id::is_valid_asset_id(asset_id) {
            return Err(ValidationError::InvalidAssetId.into());
        }
    }

    // Validate the requested folder before touching state, so a rejected
    // re-bind leaves the other patched fields unwritten too.
    if let Patch::Set(cwd) = &patch.working_directory {
        if !is_valid_working_directory(cwd.as_str()) {
            return Err(ValidationError::InvalidWorkingDirectory.into());
        }

        if let Some(owner_pet_id) = find_pet_id_by_cwd(state, cwd.as_str()) {
            if owner_pet_id != pet_id.as_str() {
                return Err(CoreError::WorkingDirectoryOccupied { owner_pet_id });
            }
        }
    }

    let mut next = state.clone();
    let mut profile_id = String::new();

    if let Some(pets) = next.get_mut("pets").and_then(|value| value.as_array_mut()) {
        for pet in pets.iter_mut() {
            if pet.get("id").and_then(|value| value.as_str()) != Some(pet_id.as_str()) {
                continue;
            }

            profile_id = pet
                .get("profileId")
                .and_then(|value| value.as_str())
                .unwrap_or_default()
                .to_string();

            let Some(object) = pet.as_object_mut() else {
                continue;
            };

            if let Some(name) = &patch.name {
                object.insert("name".to_string(), serde_json::json!(name));
            }
            if let Some(asset_id) = &patch.asset_id {
                object.insert("assetId".to_string(), serde_json::json!(asset_id));
            }
            if let Some(visible) = patch.visible {
                object.insert("visible".to_string(), serde_json::json!(visible));
            }
            if let Some(archived) = patch.archived {
                object.insert("archived".to_string(), serde_json::json!(archived));
            }
            if let Some(memo) = &patch.memo {
                object.insert("memo".to_string(), serde_json::json!(memo));
            }
            if let Some(scale) = patch.scale {
                object.insert("scale".to_string(), serde_json::json!(scale));
            }
        }
    }

    // The profile carries both the personality preset and a mirror of the pet's
    // asset id, so patch it once for whichever of the two the caller sent.
    let personality_patch = match (&patch.personality_id, personality) {
        (Some(personality_id), Some(personality)) => Some((personality_id, personality)),
        _ => None,
    };

    if personality_patch.is_some() || patch.asset_id.is_some() {
        if let Some(profiles) = next.get_mut("petProfiles").and_then(|value| value.as_array_mut()) {
            for profile in profiles.iter_mut() {
                if profile.get("id").and_then(|value| value.as_str()) != Some(profile_id.as_str()) {
                    continue;
                }

                let Some(object) = profile.as_object_mut() else {
                    continue;
                };

                if let Some((personality_id, personality)) = &personality_patch {
                    object.insert("personalityId".to_string(), serde_json::json!(personality_id));
                    object.insert("personality".to_string(), (*personality).clone());
                }
                if let Some(asset_id) = &patch.asset_id {
                    object.insert("petAssetId".to_string(), serde_json::json!(asset_id));
                }
            }
        }
    }

    match &patch.working_directory {
        Patch::Keep => {}
        Patch::Clear => apply_pet_working_directory(&mut next, pet_id.as_str(), None, ids, now),
        Patch::Set(cwd) => {
            apply_pet_working_directory(&mut next, pet_id.as_str(), Some(cwd.as_str()), ids, now)
        }
    }

    Ok(next)
}

/// Re-point one pet's registered working directory: `cwd` of `None` detaches
/// it, `Some(path)` binds it to that folder. A pet holds at most one directory
/// and a directory belongs to exactly one pet, so the pet's current entry is
/// dropped either way before a new one is appended, and the pet's back-pointer
/// is kept in step.
fn apply_pet_working_directory(
    next: &mut Value,
    pet_id: &str,
    cwd: Option<&str>,
    ids: &WorkingDirectoryIds,
    now: u64,
) {
    if let Some(directories) = next
        .get_mut("registeredWorkingDirectories")
        .and_then(|value| value.as_array_mut())
    {
        directories
            .retain(|directory| directory.get("petId").and_then(|value| value.as_str()) != Some(pet_id));
    }

    let working_directory_id = match cwd {
        Some(path) => {
            push_array(
                next,
                "registeredWorkingDirectories",
                serde_json::json!({
                    "id": ids.working_directory_id,
                    "path": path,
                    "petId": pet_id,
                    "agentSourceId": ids.agent_source_id,
                    "createdAt": now,
                    "updatedAt": now
                }),
            );
            serde_json::json!(ids.working_directory_id)
        }
        None => Value::Null,
    };

    if let Some(pets) = next.get_mut("pets").and_then(|value| value.as_array_mut()) {
        for pet in pets.iter_mut() {
            if pet.get("id").and_then(|value| value.as_str()) != Some(pet_id) {
                continue;
            }

            if let Some(object) = pet.as_object_mut() {
                object.insert("workingDirectoryId".to_string(), working_directory_id.clone());
            }
        }
    }
}

/// Permanently remove a pet, its profile, and any working directory it holds.
pub(crate) fn apply_remove_pet(state: &Value, pet_id: &PetId) -> Result<Value, CoreError> {
    let pet = state
        .get("pets")
        .and_then(|value| value.as_array())
        .and_then(|pets| {
            pets.iter()
                .find(|pet| pet.get("id").and_then(|value| value.as_str()) == Some(pet_id.as_str()))
        })
        .ok_or_else(|| CoreError::PetNotFound {
            pet_id: pet_id.as_str().to_string(),
        })?;

    let profile_id = pet
        .get("profileId")
        .and_then(|value| value.as_str())
        .unwrap_or_default()
        .to_string();

    let mut next = state.clone();
    let Some(object) = next.as_object_mut() else {
        return Ok(next);
    };

    if let Some(Value::Array(pets)) = object.get_mut("pets") {
        pets.retain(|pet| pet.get("id").and_then(|value| value.as_str()) != Some(pet_id.as_str()));
    }
    if let Some(Value::Array(profiles)) = object.get_mut("petProfiles") {
        profiles.retain(|profile| {
            profile.get("id").and_then(|value| value.as_str()) != Some(profile_id.as_str())
        });
    }
    if let Some(Value::Array(directories)) = object.get_mut("registeredWorkingDirectories") {
        directories
            .retain(|directory| directory.get("petId").and_then(|value| value.as_str()) != Some(pet_id.as_str()));
    }

    Ok(next)
}

/// Patch the app-wide settings, inserting only the fields the caller sent.
pub(crate) fn apply_settings_update(state: &Value, input: &SettingsPatch) -> Value {
    let mut next = state.clone();
    let Some(object) = next.as_object_mut() else {
        return next;
    };

    if let Some(session_command) = &input.session_command {
        object.insert("sessionCommand".to_string(), serde_json::json!(session_command));
    }
    apply_string_patch(object, "terminalShell", &input.terminal_shell);
    apply_string_patch(object, "petSourceDirectory", &input.pet_source_directory);

    next
}

/// Apply one [`Patch<String>`] to a settings object: keep leaves it, set writes
/// the string, clear writes JSON null (which the frontend parser reads as
/// "default").
fn apply_string_patch(
    object: &mut serde_json::Map<String, Value>,
    key: &str,
    patch: &Patch<String>,
) {
    match patch {
        Patch::Keep => {}
        Patch::Set(value) => {
            object.insert(key.to_string(), serde_json::json!(value));
        }
        Patch::Clear => {
            object.insert(key.to_string(), Value::Null);
        }
    }
}

/// Drop every settings key, keeping only the pet data. An absent key is what
/// the frontend parser reads as "default", so removing them is how a setting
/// goes back to its default rather than to an empty string.
pub(crate) fn apply_settings_reset(state: &Value) -> Value {
    let mut next = empty_state();

    let Some(object) = next.as_object_mut() else {
        return next;
    };

    for key in PET_DATA_KEYS {
        if let Some(value) = state.get(key) {
            object.insert(key.to_string(), value.clone());
        }
    }

    next
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state_v1::empty_state;

    fn sample_ids() -> HatchIds {
        HatchIds {
            pet_id: "pet-1".to_string(),
            profile_id: "profile-1".to_string(),
            working_directory_id: "dir-1".to_string(),
            agent_source_id: "agent-1".to_string(),
        }
    }

    fn hatch_input(cwd: Option<&str>) -> HatchPet {
        HatchPet {
            working_directory: cwd.map(WorkingDirectoryPath::new),
            asset_id: "cato".to_string(),
            name: "Rex".to_string(),
            personality_id: "playful".to_string(),
        }
    }

    fn hatched_state() -> Value {
        apply_hatch(&empty_state(), &hatch_input(Some("D:/proj")), &sample_ids(), 1000)
            .expect("hatch should succeed")
    }

    fn sample_working_directory_ids() -> WorkingDirectoryIds {
        WorkingDirectoryIds {
            working_directory_id: "dir-2".to_string(),
            agent_source_id: "agent-2".to_string(),
        }
    }

    fn blank_patch() -> PetPatch {
        PetPatch {
            name: None,
            asset_id: None,
            personality_id: None,
            visible: None,
            archived: None,
            memo: None,
            scale: None,
            working_directory: Patch::Keep,
        }
    }

    #[test]
    fn apply_hatch_appends_pet_profile_and_directory() {
        let next = apply_hatch(&empty_state(), &hatch_input(Some("D:/proj")), &sample_ids(), 1000)
            .expect("hatch should succeed");

        assert_eq!(next["schemaVersion"], 1);

        let pet = &next["pets"][0];
        assert_eq!(pet["id"], "pet-1");
        assert_eq!(pet["name"], "Rex");
        assert_eq!(pet["assetId"], "cato");
        assert_eq!(pet["profileId"], "profile-1");
        assert_eq!(pet["workingDirectoryId"], "dir-1");
        assert_eq!(pet["adoptedAt"], 1000);
        assert_eq!(pet["archived"], false);
        assert_eq!(pet["visible"], true);

        let profile = &next["petProfiles"][0];
        assert_eq!(profile["id"], "profile-1");
        assert_eq!(profile["petAssetId"], "cato");
        assert_eq!(profile["personalityId"], "playful");
        assert_eq!(profile["personality"]["extraversion"], 0.95);

        let directory = &next["registeredWorkingDirectories"][0];
        assert_eq!(directory["id"], "dir-1");
        assert_eq!(directory["path"], "D:/proj");
        assert_eq!(directory["petId"], "pet-1");
        assert_eq!(directory["agentSourceId"], "agent-1");
        assert_eq!(directory["createdAt"], 1000);
    }

    #[test]
    fn apply_hatch_rejects_occupied_cwd_case_insensitively() {
        let first = apply_hatch(&empty_state(), &hatch_input(Some("D:/Proj")), &sample_ids(), 1)
            .expect("first hatch should succeed");

        let error = apply_hatch(
            &first,
            &HatchPet {
                working_directory: Some(WorkingDirectoryPath::new("d:\\proj")),
                asset_id: "otto".to_string(),
                name: "Blue".to_string(),
                personality_id: "reserved".to_string(),
            },
            &HatchIds {
                pet_id: "pet-2".to_string(),
                profile_id: "profile-2".to_string(),
                working_directory_id: "dir-2".to_string(),
                agent_source_id: "agent-2".to_string(),
            },
            2,
        )
        .expect_err("second hatch on the same folder should be rejected");

        assert_eq!(
            error,
            CoreError::WorkingDirectoryOccupied {
                owner_pet_id: "pet-1".to_string()
            }
        );
    }

    #[test]
    fn apply_hatch_rejects_cwd_with_control_characters() {
        let error = apply_hatch(
            &empty_state(),
            &HatchPet {
                working_directory: Some(WorkingDirectoryPath::new("D:\rrealtime")),
                ..hatch_input(None)
            },
            &sample_ids(),
            1,
        )
        .expect_err("a carriage return in the path should be rejected");

        assert_eq!(error, ValidationError::InvalidWorkingDirectory.into());
    }

    #[test]
    fn apply_hatch_rejects_unknown_personality() {
        let error = apply_hatch(
            &empty_state(),
            &HatchPet {
                personality_id: "chaotic".to_string(),
                ..hatch_input(Some("D:/proj"))
            },
            &sample_ids(),
            1,
        )
        .expect_err("unknown personality should be rejected");

        assert_eq!(error, ValidationError::UnknownPersonality.into());
    }

    #[test]
    fn apply_hatch_without_a_cwd_registers_no_working_directory() {
        let next = apply_hatch(&empty_state(), &hatch_input(None), &sample_ids(), 1000)
            .expect("a folderless hatch should succeed");

        assert!(next["registeredWorkingDirectories"].as_array().unwrap().is_empty());
        assert_eq!(next["pets"][0]["workingDirectoryId"], Value::Null);
        assert_eq!(next["petProfiles"][0]["personalityId"], "playful");
    }

    #[test]
    fn apply_pet_update_patches_name_visibility_and_personality() {
        let next = apply_pet_update(
            &hatched_state(),
            &PetId::new("pet-1"),
            &PetPatch {
                name: Some("Rexy".to_string()),
                personality_id: Some("reserved".to_string()),
                visible: Some(false),
                memo: Some("likes naps".to_string()),
                ..blank_patch()
            },
            &sample_working_directory_ids(),
            2000,
        )
        .expect("update should succeed");

        let pet = &next["pets"][0];
        assert_eq!(pet["name"], "Rexy");
        assert_eq!(pet["visible"], false);
        assert_eq!(pet["archived"], false);
        assert_eq!(pet["memo"], "likes naps");

        let profile = &next["petProfiles"][0];
        assert_eq!(profile["personalityId"], "reserved");
        assert_eq!(profile["personality"]["neuroticism"], 0.82);
    }

    #[test]
    fn apply_pet_update_reskins_the_pet_and_its_profile_together() {
        let next = apply_pet_update(
            &hatched_state(),
            &PetId::new("pet-1"),
            &PetPatch {
                asset_id: Some("otto".to_string()),
                ..blank_patch()
            },
            &sample_working_directory_ids(),
            2000,
        )
        .expect("update should succeed");

        assert_eq!(next["pets"][0]["assetId"], "otto");
        assert_eq!(next["petProfiles"][0]["petAssetId"], "otto");
        assert_eq!(next["petProfiles"][0]["personalityId"], "playful");
    }

    #[test]
    fn apply_pet_update_rejects_an_unaddressable_asset_id() {
        let error = apply_pet_update(
            &hatched_state(),
            &PetId::new("pet-1"),
            &PetPatch {
                asset_id: Some("../escape".to_string()),
                name: Some("Rexy".to_string()),
                ..blank_patch()
            },
            &sample_working_directory_ids(),
            2000,
        )
        .expect_err("a path-traversing asset id must be rejected");

        assert_eq!(error, ValidationError::InvalidAssetId.into());
    }

    #[test]
    fn apply_pet_update_leaves_omitted_fields_alone() {
        let state = apply_pet_update(
            &hatched_state(),
            &PetId::new("pet-1"),
            &PetPatch {
                memo: Some("likes naps".to_string()),
                scale: Some(1.4),
                ..blank_patch()
            },
            &sample_working_directory_ids(),
            2000,
        )
        .expect("first update should succeed");

        let next = apply_pet_update(
            &state,
            &PetId::new("pet-1"),
            &PetPatch {
                name: Some("Rexy".to_string()),
                ..blank_patch()
            },
            &sample_working_directory_ids(),
            3000,
        )
        .expect("second update should succeed");

        let pet = &next["pets"][0];
        assert_eq!(pet["name"], "Rexy");
        assert_eq!(pet["memo"], "likes naps");
        assert_eq!(pet["scale"], 1.4);
    }

    #[test]
    fn apply_pet_update_rejects_unknown_pet() {
        let error = apply_pet_update(
            &hatched_state(),
            &PetId::new("pet-missing"),
            &blank_patch(),
            &sample_working_directory_ids(),
            2000,
        )
        .expect_err("unknown pet id should be rejected");

        assert_eq!(
            error,
            CoreError::PetNotFound {
                pet_id: "pet-missing".to_string()
            }
        );
    }

    #[test]
    fn apply_pet_update_clears_the_working_directory_on_clear() {
        let next = apply_pet_update(
            &hatched_state(),
            &PetId::new("pet-1"),
            &PetPatch {
                working_directory: Patch::Clear,
                ..blank_patch()
            },
            &sample_working_directory_ids(),
            2000,
        )
        .expect("clearing the working directory should succeed");

        assert!(next["registeredWorkingDirectories"].as_array().unwrap().is_empty());
        assert_eq!(next["pets"][0]["workingDirectoryId"], Value::Null);
    }

    #[test]
    fn apply_pet_update_rebinds_the_working_directory_without_leaving_the_old_one() {
        let next = apply_pet_update(
            &hatched_state(),
            &PetId::new("pet-1"),
            &PetPatch {
                working_directory: Patch::Set(WorkingDirectoryPath::new("D:/other")),
                ..blank_patch()
            },
            &sample_working_directory_ids(),
            2000,
        )
        .expect("re-binding the working directory should succeed");

        let directories = next["registeredWorkingDirectories"].as_array().unwrap();
        assert_eq!(directories.len(), 1);
        assert_eq!(directories[0]["id"], "dir-2");
        assert_eq!(directories[0]["path"], "D:/other");
        assert_eq!(directories[0]["petId"], "pet-1");
        assert_eq!(next["pets"][0]["workingDirectoryId"], "dir-2");
    }

    #[test]
    fn apply_pet_update_rejects_a_cwd_held_by_another_pet() {
        let mut state = hatched_state();
        push_array(
            &mut state,
            "pets",
            serde_json::json!({ "id": "pet-2", "workingDirectoryId": null }),
        );

        let error = apply_pet_update(
            &state,
            &PetId::new("pet-2"),
            &PetPatch {
                working_directory: Patch::Set(WorkingDirectoryPath::new("d:\\proj")),
                ..blank_patch()
            },
            &sample_working_directory_ids(),
            2000,
        )
        .expect_err("a folder already held by another pet should be rejected");

        assert_eq!(
            error,
            CoreError::WorkingDirectoryOccupied {
                owner_pet_id: "pet-1".to_string()
            }
        );
    }

    #[test]
    fn apply_pet_update_rejects_a_cwd_with_control_characters() {
        let error = apply_pet_update(
            &hatched_state(),
            &PetId::new("pet-1"),
            &PetPatch {
                working_directory: Patch::Set(WorkingDirectoryPath::new("D:\rrealtime")),
                ..blank_patch()
            },
            &sample_working_directory_ids(),
            2000,
        )
        .expect_err("a control character in the path should be rejected");

        assert_eq!(error, ValidationError::InvalidWorkingDirectory.into());
    }

    #[test]
    fn apply_remove_pet_deletes_pet_profile_and_directory() {
        let next = apply_remove_pet(&hatched_state(), &PetId::new("pet-1"))
            .expect("removal should succeed");

        assert!(next["pets"].as_array().unwrap().is_empty());
        assert!(next["petProfiles"].as_array().unwrap().is_empty());
        assert!(next["registeredWorkingDirectories"].as_array().unwrap().is_empty());
    }

    #[test]
    fn apply_remove_pet_rejects_unknown_pet() {
        assert!(apply_remove_pet(&hatched_state(), &PetId::new("pet-missing")).is_err());
    }

    #[test]
    fn apply_settings_update_patches_only_the_fields_given() {
        let state = serde_json::json!({
            "schemaVersion": 1,
            "sessionCommand": "cmd /k claude",
            "terminalShell": "C:/Windows/System32/cmd.exe",
            "petSourceDirectory": "D:/pets"
        });

        let next = apply_settings_update(
            &state,
            &SettingsPatch {
                session_command: Some("cmd /k codex".to_string()),
                terminal_shell: Patch::Keep,
                pet_source_directory: Patch::Clear,
            },
        );

        assert_eq!(next["sessionCommand"], "cmd /k codex");
        assert_eq!(next["terminalShell"], "C:/Windows/System32/cmd.exe");
        assert_eq!(next["petSourceDirectory"], Value::Null);
    }

    #[test]
    fn apply_settings_reset_restores_defaults_and_keeps_the_pets() {
        let mut state = hatched_state();
        state = apply_settings_update(
            &state,
            &SettingsPatch {
                session_command: Some("cmd /k codex".to_string()),
                terminal_shell: Patch::Set("C:/Windows/System32/cmd.exe".to_string()),
                pet_source_directory: Patch::Set("D:/pets".to_string()),
            },
        );

        let next = apply_settings_reset(&state);

        assert_eq!(next.get("sessionCommand"), None);
        assert_eq!(next.get("terminalShell"), None);
        assert_eq!(next.get("petSourceDirectory"), None);
        assert_eq!(next["schemaVersion"], 1);

        assert_eq!(next["pets"], state["pets"]);
        assert_eq!(next["petProfiles"], state["petProfiles"]);
        assert_eq!(
            next["registeredWorkingDirectories"],
            state["registeredWorkingDirectories"]
        );
    }

    #[test]
    fn apply_settings_reset_drops_a_setting_this_file_does_not_know_about() {
        let mut state = hatched_state();
        state
            .as_object_mut()
            .unwrap()
            .insert("someLaterSetting".to_string(), serde_json::json!("on"));

        let next = apply_settings_reset(&state);

        assert_eq!(next.get("someLaterSetting"), None);
        assert_eq!(next["pets"].as_array().unwrap().len(), 1);
    }

    #[test]
    fn apply_settings_reset_on_an_empty_state_is_the_empty_state() {
        assert_eq!(apply_settings_reset(&empty_state()), empty_state());
    }
}

#[cfg(test)]
pub(crate) mod tests_support {
    use super::*;
    use crate::state_v1::empty_state;

    /// A single-pet document (`pet-1` bound to `D:/proj`, playful) shared by the
    /// command and query unit tests.
    pub(crate) fn hatched_state() -> Value {
        let ids = HatchIds {
            pet_id: "pet-1".to_string(),
            profile_id: "profile-1".to_string(),
            working_directory_id: "dir-1".to_string(),
            agent_source_id: "agent-1".to_string(),
        };
        apply_hatch(
            &empty_state(),
            &HatchPet {
                working_directory: Some(WorkingDirectoryPath::new("D:/proj")),
                asset_id: "cato".to_string(),
                name: "Rex".to_string(),
                personality_id: "playful".to_string(),
            },
            &ids,
            1000,
        )
        .expect("hatch should succeed")
    }
}
