export const PLAYGROUND_TEXT = {
  title: "pets-driven playground",
  pauseAnimation: "Pause animation",
  resumeAnimation: "Resume animation",
  playNextFrame: "Play next frame",
  frameCounterPrefix: "Frame:",
  petStatusTitle: "Pet status",
  behaviorLabTitle: "Behavior lab",
  agentEventPanelTitle: "Agent hook",
  selectedPetLabel: "Selected pet",
  componentPanelTitle: "Components",
  copyStateToClipboard: "Copy state",
  copyStateCopied: "Copied",
  copyStateFailed: "Copy failed",
  hideComponentStateList: "Hide state",
  showComponentStateList: "Show state",
  noSpeech: "No speech",
  // Phase 6 — personality exposure
  oceanTitle: "Personality (OCEAN)",
  decisionTokenLabel: "Last decision",
  pendingReactionLabel: "Pending reaction",
} as const;
